services:
  web:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8000"
    networks:
      - default
      - easypanel-flow-applications

networks:
  default: {}
  easypanel-flow-applications:
    external: true
    name: easypanel-flow-applications